### ISSUE TITLE
Log gets spammed with an error

### ISSUE THREAD

**Issue by DilanRona** [dniym/IllegalStack#115]
[22:46:32] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null

**Comment by dniym** [comment]
Need more context, there should be an error that is more descriptive than just that, without more information it's impossible to find the cause

**Comment by DilanRona** [comment]
I'll go back earlier in the log and get back to you. But as I said, this is the only error generated constantly.

[07:57:51] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:51] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:52] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:52] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:53] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:53] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:54] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:54] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:55] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:55] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:56] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:56] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:57] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:57] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:58] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:58] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
[07:57:59] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null

**Comment by DilanRona** [comment]
Ok, this is the first time the error popped up.

[22:35:06] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
        at timers.fTimer.run(fTimer.java:71) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
[22:35:07] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
        at timers.fTimer.run(fTimer.java:71) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
[22:35:07] [Server thread/WARN]: [IllegalStack] Task #30 for IllegalStack v2.0.8b generated an exception
java.lang.NullPointerException: null
        at timers.fTimer.run(fTimer.java:71) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [server.jar:git-Spigot-cbd1a1b-009d8af]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

Hopefully it will help a bit more.

**Comment by dniym** [comment]
Current Version is now 2.4.0 could you let me know if you're still experiencing problems with this version?
