### ISSUE TITLE
InfernalMobs - Could not pass event EntityMountEvent to IllegalStack

### ISSUE THREAD

**Issue by s1h4d0w** [dniym/IllegalStack#119]
I have InfernalMobs running on my 1.16.5 Paper server and it throws an error every once a while, I assume it happens when IM spawns on of their boss mobs.

IllegalStack 2.2.2a
Paper 1.16.5

```
[13:27:08 ERROR]: Could not pass event EntityMountEvent to IllegalStack v2.2.2a
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.entity.CraftSkeleton cannot be cast to class org.bukkit.entity.Player (org.bukkit.craftbukkit.v1_16_R3.entity.CraftSkeleton and org.bukkit.entity.Player are in unnamed module of loader 'app')
        at me.dniym.listeners.fListener.onEntityMount(fListener.java:578) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor529.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-545]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-545]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-545]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.Entity.addPassenger(Entity.java:2082) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.Entity.a(Entity.java:2015) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.EntityInsentient.a(EntityInsentient.java:1374) ~[patched_1.16.5.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.addPassenger(CraftEntity.java:676) ~[patched_1.16.5.jar:git-Paper-545]
        at io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs.giveMobGear(infernal_mobs.java:2101) ~[?:?]
        at io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs.lambda$0(infernal_mobs.java:348) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1301) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.5.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-545]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
