### ISSUE TITLE
NBTAPI error on PlayerJoinEvent

### ISSUE THREAD

**Issue by Corenb** [dniym/IllegalStack#12]
`>.... [19:52:06 ERROR]: Could not pass event PlayerJoinEvent to IllegalStack v2.0.9a
java.lang.NoClassDefFoundError: de/tr7zw/nbtapi/NBTItem
at utils.NBTStuff.isBadShulker(NBTStuff.java:129) ~[?:?]
at main.fListener.onPlayerJoin(fListener.java:1717) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor119.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-234]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-234]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-234]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-234]
at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191) ~[patched_1.14.4.jar:git-Paper-234]
at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.14.4.jar:git-Paper-234]
at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.4.jar:git-Paper-234]
at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.14.4.jar:git-Paper-234]
at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.14.4.jar:git-Paper-234]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1255) ~[patched_1.14.4.jar:git-Paper-234]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-234]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-234]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-234]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Comment by dniym** [comment]
This is due to NBTApi not being installed on your server, however this is an optional component and the plugin should detect its absence instead of throwing an error.  I will upload a fix for this shortly.
