### ISSUE TITLE
Async Packet - Couldn't get an entity from id - The method getWorld is not supported for temporary players

### ISSUE THREAD

**Issue by Baterka** [dniym/IllegalStack#131]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): 2.4.2
- Spigot/Paper Version Number (`/version`): AirplanePurpur 1.17.1
- Output of `/version`: AirplanePurpur version git-AirplanePurpur-31 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2040bab on HEAD)

**Describe the bug**
Multiple errors spammed in console:
```
[20:00:08 ERROR]: [IllegalStack/pLisbListener] Async Packet - Couldn't get an entity from id:
java.lang.UnsupportedOperationException: The method getWorld is not supported for temporary players.
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.delegate(TemporaryPlayerFactory.java:166) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler.getWorld(Unknown Source) ~[ProtocolLib.jar:?]
        at main.java.me.dniym.listeners.pLisbListener$2$1.run(pLisbListener.java:88) ~[IllegalStack-2.4.2.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-AirplanePurpur-31]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-AirplanePurpur-31]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[patched_1.17.1.jar:git-AirplanePurpur-31]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:494) ~[patched_1.17.1.jar:git-AirplanePurpur-31]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-AirplanePurpur-31]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-AirplanePurpur-31]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-AirplanePurpur-31]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**To Reproduce**
Hapenning randomly

**Plugins being used on the server**
AdvancedAchievements, AdvancedDevelopmentLibrary, AntiAFKPlus, AntiXrayHeuristics, AnvilRestrict, ArmorStandTools, ChangeSlots, ChatControl, ChestSort, Chunky, ChunkyBorder, ClearLag, CMI, CMIEInjector*, CMILib, CommandBlocks, CommandHook, CoreProtect, CrateReloaded, Custom, CustomLottery, CustomStatTrak, CustomWiper, DisableElytra, DiscordSRV, EditableSign, EntityDetection, ExtraContexts*, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), FlexLevel, floodgate, GadgetsMenu, Insights, InteractiveBoard, JumpPads, KeepItems*, LagAssist, LibsDisguises, LuckPerms, Minepacks, MobsManager, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, NBTAPI, NerfPhantoms, NoBedExplosions, NoEndCrystals, NoFlyZone, PerWorldInventory, PlaceholderAPI, PlayerWarps, PlugMan, POSTRequest*, PremiumVanish, ProtocolLib, QuickShop, Residence, ShopGUIPlus, SkinsRestorer, spark, SSX-Connector*, TAB-BukkitBridge, TimeIsMoney, TokenManager, TradePlus, TrMenu, TryMe, UltimateAutoRestart, UltraRepair, Vault, VillagerModifications, VoidGen, Voting, VotingPlugin, WebConnector, WildStacker, WorldGuard, WorldGuardDisableCollisions, WorldGuardExtraFlags, zAuctionHouseV3

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
