### ISSUE TITLE
Gives error with Grief Defender plugin

### ISSUE THREAD

**Issue by AlterDimension** [dniym/IllegalStack#135]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): 2.4.2a
- Spigot/Paper Version Number (`/version`): 1618
- Output of `/version`: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Describe the bug**
[18:14:43 ERROR]: Could not pass event PortalCreateEvent to GriefDefender v2.0.1
java.lang.NoSuchMethodError: org.bukkit.event.world.PortalCreateEvent.getEntity()Lorg/bukkit/entity/Entity;
        at com.griefdefender.listener.PlayerEventHandler.onPlayerPortalCreate(PlayerEventHandler.java:1172) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor54.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.BlockPortal$Shape.createPortal(BlockPortal.java:377) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.BlockPortal.b(BlockPortal.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.BlockFire.onPlace(BlockFire.java:330) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:277) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:551) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1011) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**To Reproduce**
1. Claim a land with Grief Defender
2. Lit a nether portal
3. Error spammed console

**Plugins being used on the server**
IllegalStacks, GriefDefender

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [x] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dniym** [comment]
Ah that's because the error isn't in IllegalStack it's in grief defender, you'll need to contact the author of that plugin for a fix.  If you look at the error it only mentions grief defender
