### ISSUE TITLE
Console message

### ISSUE THREAD

**Issue by DarkCarlox** [dniym/IllegalStack#138]
Hello, I just added the plugin and I noticed that the console sends me a message so I don't know if it is a bug or normal
`to IllegalStack v2.4.2a
```
Caused by: java.lang.ClassCastException
[13:05:58] [Server thread/ERROR] [Minecraft]: Could not pass event InventoryMoveItemEvent to IllegalStack v2.4.2a
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:788465c-DEV]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:788465c-DEV]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:788465c-DEV]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:517) [SimplePluginManager.class:788465c-DEV]
        at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:264) [avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:172) [avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:157) [avw.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2160) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:852) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:988) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.ClassCastException
[13:05:58] [Server thread/ERROR] [Minecraft]: Could not pass event InventoryMoveItemEvent to IllegalStack v2.4.2a
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:788465c-DEV]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:788465c-DEV]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:788465c-DEV]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:517) [SimplePluginManager.class:788465c-DEV]
        at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:264) [avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:172) [avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:157) [avw.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2160) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:852) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:988) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.ClassCastException
```
I use version 1.12.2 with magma server

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
