### ISSUE TITLE
Could not pass event InventoryOpenEvent

### ISSUE THREAD

**Issue by Bayanicool** [dniym/IllegalStack#167]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): 2.8 / [92mIllegalStack[97m version .8
- Spigot/Paper Version Number (`/version`): 2.8
- Output of `/version`: Nothing

**Describe the bug**
IllegalStack keeps popping up this "- [Wed 18:49:15 ERROR Minecraft] Could not pass event InventoryOpenEvent to IllegalStack v2.8" in console.

LONGER: 
"- [Wed 18:49:15 ERROR Minecraft] Could not pass event InventoryOpenEvent to IllegalStack v2.8
java.nio.charset.UnsupportedCharsetException: false
    at java.base/java.nio.charset.Charset.forName(Charset.java:528)
    at IllegalStack-2.8.jar//main.java.me.dniym.listeners.fListener.onShulkerCheck(fListener.java:1321)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor886.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
    at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1399)
    at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1566)
    at net.minecraft.world.level.block.ChestBlock.use(ChestBlock.java:269)
    at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:1177)
    at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:581)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1960)
    at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37)
    at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9)
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51)
    at net.minecraft.server.TickTask.run(TickTask.java:18)
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
    at net.minecraft.util.thread"

**To Reproduce**
THIS ERROR JUST HAPPENS ALL THE TIME

**Plugins being used on the server**
  [Wed 18:52:29 INFO ] [97mServer Plugins (50):
  [Wed 18:52:29 INFO ] [36mPaper Plugins:
  [Wed 18:52:29 INFO ]  [90m- [92mRoseStacker
  [Wed 18:52:29 INFO ] [33mBukkit Plugins:
  [Wed 18:52:29 INFO ]  [90m- [92mAuctionHouse, [92mBetterRTP, [92mBuycraftX, [92mChatItem, [92mChatManager, [92mCitizens, [92mCoreProtect, [92mDecentHolograms, [92mDeluxeMenus, [92mDiamondBank
  [Wed 18:52:29 INFO ]  [33m*[92mDiscordServerConsole, [92mDiscordSRV, [92mEssentials, [92mEssentialsChat, [92mEssentialsSpawn, [92mFastAsyncWorldEdit, [92mfloodgate, [92mGeyser-Spigot, [92mGraves, [92mGriefPrevention
  [Wed 18:52:29 INFO ]  [92mHeadDrops, [92mIllegalStack, [92mIllegalStack, [92mInventoryRollbackPlus, [92mLPC, [92mLuckPerms, [92mmcMMO, [92mMultiverse-Core, [92mNBTAPI, [92mNoteBlockAPI
  [Wed 18:52:29 INFO ]  [92mPlaceholderAPI, [92mPlayerWarps, [92mPlugManX, [92mProtocolLib, [92mServerListPlus, [92mSignShop, [92mSilkSpawners_v2, [92mSkript, [92mSlimefun, [91mTAB
  [Wed 18:52:29 INFO ]  [91mTradeSystem, [92mUltimateAutoRestart, [92mVault, [92mViaBackwards, [92mViaRewind, [92mViaVersion, [92mVotifier, [92mVotingPlugin, [92mWorldGuard

**Checklist**:

- [YES] I included all information required in the sections above
- [YES] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [YES] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [YES] I made sure the bug/error is not caused by any other plugin

**Comment by dniym** [comment]
Output of /version: Nothing 

???  /ver in the console should output what version of spigot/minecraft server you are running.

**Comment by Bayanicool** [comment]
Oh, sorry I am running Latest Revision of PAPERMC and 1.20.1 /ver does work. /version does not

**Comment by dniym** [comment]
so the error in this points to another method in illegalstack but its not showing me where, can you please provide me with a bigger block of the error?  specifically it should mention a line in Protections.java

**Comment by dniym** [comment]
IllegalStack v 2.8.5 is out now, could you please check to see if this issue still persists and if so provide us with the full error message.
