### ISSUE TITLE
IllegalStack doesnt load. Scheduler Period may not be <= 0

### ISSUE THREAD

**Issue by JeffHD** [dniym/IllegalStack#169]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): v2.9.2
- Spigot/Paper Version Number (`/version`): 1.20.1
- Output of `/version`: This server is running Paper version git-Paper-54 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 8582999)
You are running the latest version
Previous version: git-Paper-49 (MC: 1.20.1)

**Describe the bug**
IllegalStack doesnt start with following error: 
```
[Server thread/ERROR]: Error occurred while enabling IllegalStack v2.9.2 (Is it up to date?)
java.lang.IllegalArgumentException: Period may not be <= 0
	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler.runAtFixedRate(FoliaAsyncScheduler.java:113) ~[paper-1.20.1.jar:?]
	at main.java.me.dniym.utils.Scheduler.runTaskTimerAsynchronously(Scheduler.java:215) ~[IllegalStack.jar:?]
	at main.java.me.dniym.IllegalStack.onEnable(IllegalStack.java:460) ~[IllegalStack.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-54]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-54]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-54]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-54]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**To Reproduce**
Start the server with the plugin and the error comes up.

**Plugins being used on the server**

**Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [X] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by JeffHD** [comment]
Okay i found the error. The config was once generated with ItemScanTimer:0. I always used an unedited config so i doesnt expected that to be the issue since it always worked before. I have set it to 10 and now it works
