### ISSUE TITLE
io.papermc.paper.threadedregions.scheduler.AsyncScheduler org.bukkit.Server.getAsyncScheduler()

### ISSUE THREAD

**Issue by PaxJaromeMalues** [dniym/IllegalStack#170]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): IllegalStack version 2.9.3
- Spigot/Paper Version Number (`/version`): Paper 1.18.2 - 388
- Output of `/version`: git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)

**Describe the bug**
Error message
```console
[00:17:40 ERROR]: Error occurred while disabling IllegalStack v2.9.3 (Is it up to date?)
java.lang.NoSuchMethodError: 'io.papermc.paper.threadedregions.scheduler.AsyncScheduler org.bukkit.Server.getAsyncScheduler()'
	at main.java.me.dniym.IllegalStack.onDisable(IllegalStack.java:903) ~[IllegalStack-2.9.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:555) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.disablePlugins(CraftServer.java:494) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:972) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:803) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:932) ~[paper-1.18.2.jar:git-Paper-388]
	at org.spigotmc.RestartCommand.shutdownServer(RestartCommand.java:92) ~[paper-1.18.2.jar:git-Paper-388]
	at org.spigotmc.RestartCommand.restart(RestartCommand.java:61) ~[paper-1.18.2.jar:git-Paper-388]
	at org.spigotmc.RestartCommand.restart(RestartCommand.java:40) ~[paper-1.18.2.jar:git-Paper-388]
	at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1545) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**To Reproduce**
1. Run an unknown command. In this case: `restart`
2. Receive error message

**Plugins being used on the server**
```console
Plugins (65): 3DItems, AggressiveAnimals, AntiFarm, BetterMobs, BFV, BlueMap, BlueSlimeCore, Celeste, Chunky, ChunkyBorder, CMILib, CookMe, CourierNew, CustomCrafting, CustomItems, CustomUniverse, DeadlyDisasters, DisableChorusFruit*, DisableEnderPearl*, DisableRecipe, Drycell, ErraticExplosions, FoodSpoilage, HoloMobHealth, hydrationPlugin, IllegalStack, ItemBridge, Jobs, LevelledMobs, LuckPerms, Magic, Maintenance, MidensFoods, NBTAPI, NexEngine, NoBedSleep, Novaconomy, NoWater*, PhysicsToGo, PlaceholderAPI, PluginManager, ProtocolLib, ProximityChat*, QuickTax, RealisticSeasons, RespawnX, RHLeafDecay, RoseLoot, ServerListPlus, SimpleTabList*, Skript, SnowierSnow, StackableItems, SunLight, TerraformGenerator, Timer, UltimateAutoRestart, UltimateTimber, Vault, voicechat, Weight-RPG, WolfyUtilities, WorldEdit, WorldEditSUI, WorldGuard
```

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [x] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [] I made sure the bug/error is not caused by any other plugin
^^ that is an insane requirement my dude, get rid of it

**Comment by dniym** [comment]
Should be fixed as of IllegalStack ver 2.9.8
