### ISSUE TITLE
IllegalStack using Folia Async on Paper 1.20.1? Causing errors at shutdown/restart

### ISSUE THREAD

**Issue by veteranmina** [dniym/IllegalStack#171]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): 2.9.4
- Spigot/Paper Version Number (`/version`): Paper-1.20.1-58
- Output of `/version`:

**Describe the bug**
Upon shutdown/restart of server console spam occurs from IllegalStack preventing server on task.

**To Reproduce**
1. Turn on server
2. Run either shutdown or restart of server, logs are then flooded with IllegalStack errors below:

```
[22:00:21] [Folia Async Scheduler Thread #5/WARN]: [IllegalStack] Async task for IllegalStack v2.9.2 generated an exception
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler.runDelayed(FoliaEntityScheduler.java:64) ~[paper-1.20.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler.run(FoliaEntityScheduler.java:51) ~[paper-1.20.1.jar:?]
	at main.java.me.dniym.utils.Scheduler.executeOrScheduleSync(Scheduler.java:71) ~[IllegalStack-2.9.2a.jar:?]
	at main.java.me.dniym.timers.fTimer.run(fTimer.java:265) ~[IllegalStack-2.9.2a.jar:?]
	at main.java.me.dniym.utils.Scheduler.lambda$runTaskTimerAsynchronously$14(Scheduler.java:215) ~[IllegalStack-2.9.2a.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Plugins being used on the server**
![image](https://github.com/dniym/IllegalStack/assets/1810464/583deab9-11da-41d4-b181-666791219218)

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [X] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by veteranmina** [comment]
I noticed the log shows 2.9.2, however before posting this I saw version 2.9.4 was out however it also produced the same error.
