### ISSUE TITLE
Task error

### ISSUE THREAD

**Issue by LyFl0w** [dniym/IllegalStack#190]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): 2.9.9
- Spigot/Paper Version Number (`/version`): 4133-Spigot-b698b49-bb9a6e9
- Output of `/version`: (MC: 1.20.5)

**Describe the bug**
`[IllegalStack] Plugin IllegalStack v2.9.9 generated an exception while executing task 2
java.lang.NoSuchMethodError: 'boolean org.bukkit.Server.isStopping()'
        at main.java.me.dniym.timers.fTimer.run(fTimer.java:122) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4133-Spigot-b698b49-bb9a6e9]
        at org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4133-Spigot-b698b49-bb9a6e9]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

**To Reproduce**
1. Run  server
2. See error in console

**Plugins being used on the server**

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [X] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Loving11ish** [comment]
Hmmm, ok.  This is due to an issue with the plugins internal scheduler.  We will fix this in the next update.
