### ISSUE TITLE
Unable to start on paperspigot 1.20.6 DEV

### ISSUE THREAD

**Issue by KweezyCode** [dniym/IllegalStack#192]
```
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at IllegalStack.jar/main.java.me.dniym.IllegalStack.setVersion(IllegalStack.java:1030) ~[IllegalStack.jar:?]
	at IllegalStack.jar/main.java.me.dniym.IllegalStack.onEnable(IllegalStack.java:356) ~[IllegalStack.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

```
/version
[16:19:16 INFO]: Checking version, please wait...
[16:19:17 INFO]: This server is running Paper version 1.20.6-115-master@9d6f2cc (2024-05-28T14:55:16Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
```

**Comment by Loving11ish** [comment]
We are working on 1.20.6 compatibility.  The issue is because CraftBukkit have removed the Minecraft version string from their packages, so all of us devs of plugins are having to fix a lot of breakages.

**Comment by KweezyCode** [comment]
may I close this ticket?

**Comment by dniym** [comment]
Yes, sorry please do
