### ISSUE TITLE
Error in Folia 1.20.6

### ISSUE THREAD

**Issue by PHEyejixHello** [dniym/IllegalStack#200]
[13:02:14 WARN]: [IllegalStack] Entity task for IllegalStack v2.9.12-SNAPSHOT-01 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.potion.PotionData.getType()" because "pd" is null
        at IllegalStack-2.9.12-SNAPSHOT-01 (1).jar/main.java.me.dniym.checks.BadPotionCheck.checkPotion(BadPotionCheck.java:37) ~[IllegalStack-2.9.12-SNAPSHOT-01 (1).jar:?]
        at IllegalStack-2.9.12-SNAPSHOT-01 (1).jar/main.java.me.dniym.timers.fTimer.lambda$run$16(fTimer.java:649) ~[IllegalStack-2.9.12-SNAPSHOT-01 (1).jar:?]
        at IllegalStack-2.9.12-SNAPSHOT-01 (1).jar/main.java.me.dniym.utils.Scheduler.lambda$executeOrScheduleSync$0(Scheduler.java:54) ~[IllegalStack-2.9.12-SNAPSHOT-01 (1).jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:168) ~[luminol-1.20.6.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:115) ~[luminol-1.20.6.jar:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1691) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by PHEyejixHello** [comment]
look like is.getItemMeta() returned null
