### ISSUE TITLE
Could not pass PlayerFishEvent

### ISSUE THREAD

**Issue by xKubuuus** [dniym/IllegalStack#204]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): v2.9.12a
- Spigot/Paper Version Number (`/version`): Pufferfish 1.21.1-15-HEAD@3554f78
- Output of `/version`: ^

**Describe the bug**
We dynamically create and delete worlds on the server, which causes the following error:
```
[16:40:50] [Server thread/ERROR]: Could not pass event PlayerFishEvent to IllegalStack v2.9.12a
java.lang.IllegalArgumentException: World unloaded
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
at org.bukkit.Location.getWorld(Location.java:112) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at IllegalStack-2.9.12a.jar/main.java.me.dniym.fishing.FishAttempt.isBlackListedSpot(FishAttempt.java:106) ~[IllegalStack-2.9.12a.jar:?]
at IllegalStack-2.9.12a.jar/main.java.me.dniym.listeners.fListener.onFish(fListener.java:3362) ~[IllegalStack-2.9.12a.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor894.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-15-3554f78]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.world.entity.projectile.FishingHook.retrieve(FishingHook.java:543) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.world.item.FishingRodItem.use(FishingRodItem.java:33) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.world.item.ItemStack.use(ItemStack.java:603) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:488) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2033) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1544) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1521) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1514) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [x] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dniym** [comment]
Interesting, I'll see what we can do to fix that.  It's amazing you're not having issues with other plugins with this.

**Comment by xKubuuus** [comment]
and?
