### ISSUE TITLE
report error

### ISSUE THREAD

**Issue by xANoyU** [dniym/IllegalStack#37]
[11:37:38] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to IllegalStack v2.1.2b
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:69) ~[EventExecutor$2.class:git-CatServer-1.12.2
-2fbf24f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cat
Server-1.12.2-2fbf24f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-
CatServer-1.12.2-2fbf24f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-
CatServer-1.12.2-2fbf24f]
        at net.minecraftforge.items.VanillaInventoryCodeHooks.insertHook(VanillaInventoryCodeHooks.java:172) [VanillaInv
entoryCodeHooks.class:git-CatServer-1.12.2-2fbf24f]
        at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:231) [avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:174) [avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:159) [avw.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2133) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:756) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.ClassCastException: catserver.server.inventory.CraftCustomContainer cannot be cast to org.bukkit.bl
ock.Hopper
        at main.fListener.onHopperXfer(fListener.java:466) ~[?:?]
        at catserver.server.executor.asm.generated.GeneratedEventExecutor191.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-CatServer-1.12.2
-2fbf24f]
        ... 14 more

**Comment by dniym** [comment]
Hmmm that’s odd, what server version are you running? And what plugins?  /plugins

**Comment by xANoyU** [comment]
1.12.2 
a lot of plugins
can i send a screenshot？
https://i.loli.net/2020/05/04/sNHjqSkbIadKVec.png
https://i.loli.net/2020/05/04/KDOF2gU3CpY64An.png
https://i.loli.net/2020/05/04/MSB6AzO8VxECw71.png

**Comment by dniym** [comment]
Anything dealing with hoppers specifically?

**Comment by xANoyU** [comment]
yes 
This plug-in says that it can repair the funnel of DIM-1 to copy items Bug
i can turn it off

**Comment by dniym** [comment]
Ah, may be the two conflicting.  Turn one of them off and the error should go away

**Comment by xANoyU** [comment]
> Ah, may be the two conflicting. Turn one of them off and the error should go away

It didn't seem to work. I tried to remove the plugin, but still report error 

[11:58:40] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to IllegalStack v2.1.2b
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:69) ~[EventExecutor$2.class:git-CatServer-1.12.2
-2fbf24f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cat
Server-1.12.2-2fbf24f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-
CatServer-1.12.2-2fbf24f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-
CatServer-1.12.2-2fbf24f]
        at net.minecraftforge.items.VanillaInventoryCodeHooks.insertHook(VanillaInventoryCodeHooks.java:172) [VanillaInv
entoryCodeHooks.class:git-CatServer-1.12.2-2fbf24f]
        at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:231) [avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:174) [avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:159) [avw.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2133) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:756) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.ClassCastException

**Comment by dniym** [comment]
at net.minecraftforge.items.
Are you running this on a forge server?

**Comment by xANoyU** [comment]
> at net.minecraftforge.items.
> Are you running this on a forge server?

yes

**Comment by dniym** [comment]
that looks like it’s failing In the PreventHoppersToUnloadedChunks protection. 

You can try to disable it by doing this:

To enable / disable this protection use the following command: /istack toggle PreventHoppersToUnloadedChunks

(No restart required)

But it may appear in another protection if you get another error let me know.  It seems like a mod added a custom hopper object and IllegalStack can’t interface with it
