### ISSUE TITLE
Error in console V2.1.2d

### ISSUE THREAD

**Issue by WolverStones** [dniym/IllegalStack#47]
/istack reload

[17:05:41 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'istack' in plugin IllegalStack v2.1.2d
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1872) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1680) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1154) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1147) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1123) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:966) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
at enums.Protections.update(Protections.java:760) ~[?:?]
at main.IllegalStack.loadConfig(IllegalStack.java:385) ~[?:?]
at main.IllegalStack.ReloadConfig(IllegalStack.java:587) ~[?:?]
at commands.iStackCommand.onCommand(iStackCommand.java:32) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Tuinity-"6eb873c"]
... 17 more

[17:07:22 INFO]: Previous version: git-Tuinity-"5cf4104" (MC: 1.15.2)

**Comment by dniym** [comment]
Known issue should be fixed soon, if you use the in game config tool /istack prot you can configure the plugin in game with no need to reload / restart the server

**Comment by WolverStones** [comment]
> Known issue should be fixed soon, if you use the in game config tool /istack prot you can configure the plugin in game with no need to reload / restart the server

ok thank you for your quick reply
