### ISSUE TITLE
NPE on player connect

### ISSUE THREAD

**Issue by SlimeDog** [dniym/IllegalStack#67]
Spigot 1.16.1 (jenkins 2830)
ProtocolLib 4.6.0-SNAPSHOT-b464
IllegalStack 2.1.7, upgrade from 2.1.6

No changes to configuration or server content or player inventory. No illegal items in player inventory. On player connect, four of these
```
[10:56:30] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to IllegalStack v2.1.7
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        at net.minecraft.server.v1_16_R1.TileEntityHopper.k(TileEntityHopper.java:199) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        at net.minecraft.server.v1_16_R1.TileEntityHopper.a(TileEntityHopper.java:135) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        at net.minecraft.server.v1_16_R1.TileEntityHopper.tick(TileEntityHopper.java:117) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        at net.minecraft.server.v1_16_R1.World.tickBlockEntities(World.java:678) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:418) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1106) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at me.dniym.enums.Protections.isWhitelisted(Protections.java:938) ~[?:?]
        at me.dniym.checks.RemoveItemTypesCheck.shouldRemove(RemoveItemTypesCheck.java:33) ~[?:?]
        at me.dniym.checks.CheckUtils.CheckEntireInventory(CheckUtils.java:112) ~[?:?]
        at me.dniym.listeners.fListener.onHopperXfer(fListener.java:656) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.1.jar-2020-07-18-0600:git-Spigot-d4cbb64-2361cb8]
        ... 14 more
```

**Comment by SlimeDog** [comment]
Confirmed fixed 2.1.7a
Thanks.
