### ISSUE TITLE
Could not pass event InventoryOpenEvent to IllegalStack v2.1.8

### ISSUE THREAD

**Issue by notbike** [dniym/IllegalStack#76]
Every time i open a container, such as a chest, a crafting table, this error will pop up.

Server platform: Paper
MC Ver.: 1.16.2
plugin ver.: 2.1.8

[15:30:21] [Server thread/ERROR]: Could not pass event InventoryOpenEvent to IllegalStack v2.1.8
java.lang.NoClassDefFoundError: net/brcdev/shopgui/gui/gui/OpenGui
	at me.dniym.enums.Protections.isThirdPartyInventory(Protections.java:979) ~[?:?]
	at me.dniym.listeners.fListener.onShulkerCheck(fListener.java:928) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor122.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1245) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.EntityPlayer.openContainer(EntityPlayer.java:1263) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.BlockWorkbench.interact(SourceFile:31) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.interact(BlockBase.java:572) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:507) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1445) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by dniym** [comment]
closed due to OP not answering.
