### ISSUE TITLE
InventoryMoveItemEvent Error

### ISSUE THREAD

**Issue by levtey** [dniym/IllegalStack#82]
Hi,

Our server starts off fine, but as time goes by, the console gets spammed with this error:
[10:56:10] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to IllegalStack v2.1.4
java.lang.StackOverflowError: null
	at me.dniym.enums.Msg.getValue(Msg.java:252) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
	at me.dniym.enums.Msg.getValue(Msg.java:255) ~[?:?]
and that line repeats for a while

**Comment by dniym** [comment]
Hmmmm I’ll check when I get back home, as a temp fix you can turn off hopper checks

**Comment by dniym** [comment]
Oh, you're using a super old version of IllegalStack, no way for me to even guess as to what is causing that.   Please update to the latest version (currently 2.2.0)  Your config will remain intact and new options will be added to it.  Just watch the console when you restart and you'll see what has been added.   This should resolve your issue if not feel free to open a new issue.
